### ISSUE TITLE
Project

### ISSUE THREAD

**Issue by alextsk** [alexanderkif/modifiable-slider#2]
в проекте сам компонент затерялся среди лишнего кода, который нужен только для демонстрации, надо их как-то разделить, папку demo например сделать. и public возможно лишняя папка
в общем, надо прибраться)
если папку dist используешь для подключения то лучше хранить в ней минифицированную версию самого компонента,  с демкой не смешивая. если у тебя подключение одним файлом то его можно вообще в корне хранить, ( самый шик в отдельной ветке, но это будет сложнее подключать, не обязательно)

**Comment by alexanderkif** [comment]
привет. в корне оставил только sliderm3.js, остальное убрал в demo. теперь sliderm3.js собирается отдельно от main.js, и через npm run build мини версия.

**Comment by alextsk** [comment]
еще демо вынести на один уровень выше. в src должен остаться только сам компонент и тесты к нему

**Comment by alexanderkif** [comment]
вынес.
