### ISSUE TITLE
Плагин JQuery

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [alexanderkif/modifiable-slider#5]
Согласно заданию слайдер должен быть реализован плагином JQuery. https://rizzoma.com/topic/d5c429337bcaa70548fb5aeedee6d92b/0_b_8ndo_78h7o/  Думаю эти статьи помогут разобраться https://learn.jquery.com/plugins/basic-plugin-creation/ http://jquery.page2page.ru/index.php5/%D0%A1%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_%D0%BF%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD%D0%B0_jQuery

**Comment by alexanderkif** [comment]
как-то так, цепочки поддерживает.
