### ISSUE TITLE
Config.js

### ISSUE THREAD

**Issue by GoodDayTodayOkey** [alexanderkif/modifiable-slider#6]
Этого файла по сути не должно быть. Код где ты устанавливаешь дефолтные значения, нужно вынести в JQuery плагин(желательно их парсить из json). А та логика что связна с проверками должна находиться в модели.

**Comment by alexanderkif** [comment]
сделал

**Comment by GoodDayTodayOkey** [comment]
Так не пойдет, почитай вот здесь про добавление свойств плагину http://jquery.page2page.ru/index.php5/%D0%A1%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5_%D0%BF%D0%BB%D0%B0%D0%B3%D0%B8%D0%BD%D0%B0_jQuery

**Comment by alexanderkif** [comment]
а так?

**Comment by GoodDayTodayOkey** [comment]
Почти имеется еще парочку замечаний: 1) 
![Снимок экрана от 2019-04-24 19-56-10](https://user-images.githubusercontent.com/31854808/56661073-2c59fd00-66cb-11e9-9e74-6274c2530e66.png)  здесь код сам тебе подсказывает что это логика, а следовательно ее место в модели 2) У тебя сейчас идет путаница с получением данных из data.json. Defaults это то что есть в каждом слайдере, поэтому такой строчки не должно быть $(`.${dataJson.sliderClass}`).modSlider(dataJson.defaults) их нужно в файле с объявлением плагина распарить (JSON.parse()) из даты и предавать в $.extend(), а в index.js из demo должны парситься значения для слайдеров и предаваться внутрь твоего плагина, для этого обычный forEach подойдет. Не нужно их сначала передавать в pug, затем устанавливать в дата атрибуты, потом лезть jsсом чтобы их снова оттуда достать и затем пропихивать в слайдер.

**Comment by alexanderkif** [comment]
1) как бы сделал
2) т.е. не использовать датасет вообще? сделать как в jquery? 
у меня начальная задумка слайдера была такой: создаем див с классом слайдера, подключаем единственный файл js и все... далее хоть кто читает значения из датасета, если нужно.
а теперь получается я делаю как все, типа "как надо". тогда вопрос: а для чего? оно уже есть. бери - используй. открывай - изучай, как сделано. для чего колесо изобретать?

**Comment by GoodDayTodayOkey** [comment]
2. Зачастую бывает что либы не подходят по своему функционалу, и приходится писать свою. Поэтому стажеры и учатся делать различные элементы плюсом правильно писать логику для их управления. Не мало важен тот, что доверяясь либе - ты доверяешься чужому коду)  Хорошо, если задумка была именно такая, то можно оставить так.
